name: CI

on:
  push:
    branches: [main, dev, assignment-8-cicd]
  pull_request:
    branches: [main]

jobs:
  evaluate-model:
    runs-on: ubuntu-latest
    needs: train-model
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: Install dependencies
        run: make install

      - name: running evaluation
        run: source .venv/bin/activate &&  make run-pipeline && make run-evaluation
  train-model:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python 3.11
        run: uv python install 3.11

      - name: Install dependencies
        run: make install

      - name: running training
        run: source .venv/bin/activate && make run-pipeline
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: make install

      - name: Run code quality checks (Linting, Formatting Check, Type Check, Pre-commit hooks)
        run: make check-all

      - name: Run tests with coverage
        run: make test-cov
